package com.dds.views;

import com.dds.DAO.ProjectDAO;
import com.dds.DAO.SiteDAO;
import com.dds.model.Project;
import com.dds.model.Site;
import com.dds.util.AlertUtil;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;

public class FormProjetos extends javax.swing.JFrame {

    private Project project = null;
    private ProjectDAO projectDAO = new ProjectDAO();
    private SiteDAO siteDAO = new SiteDAO();


    public FormProjetos() {
        initComponents();
        this.project = new Project();
        this.carregarListaDeSites();
    }

    public FormProjetos(Project project) {
        this();
        this.project = project;
        this.txtDescricao.setText(this.project.getDescription());
    }

    public void carregarListaDeSites() {
        DefaultListModel model = new DefaultListModel();
        List<Integer> indices = new ArrayList<>();
        int i = 0;
        for (Site site : this.siteDAO.findAll()) {
            model.addElement(site.getId() + " - " + site.getDescription());
            if (!(this.project.getId() == null)) {
                if (this.project.getSites().size() > 0) {
                    for (Site siteItem : this.project.getSites()) {
                        if (siteItem.getId() == site.getId()) {
                            indices.add(i);
                        }
                    }
                }
            }
            i++;
        }

        this.listSites.setModel(model);
        for (int id : indices) {
            System.out.println("seleciona");
            this.listSites.setSelectedIndex(id);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSites = new javax.swing.JList<>();
        btGerenciarSites = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btHabilitar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btGerenciarSites1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 236, 236));
        setResizable(false);

        jLabel1.setText("Descrição:");

        jLabel2.setText("Sites:");

        listSites.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSites.setSize(new java.awt.Dimension(90, 130));
        jScrollPane1.setViewportView(listSites);

        btGerenciarSites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icons/add.png"))); // NOI18N
        btGerenciarSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarSitesActionPerformed(evt);
            }
        });

        jLabel3.setText("Ferramentas:");

        btHabilitar.setText("Sincronizar com Slack");
        btHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHabilitarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Formulário de Projeto");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btGerenciarSites1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icons/remove.png"))); // NOI18N
        btGerenciarSites1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarSites1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHabilitar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGerenciarSites1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btGerenciarSites, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btGerenciarSites, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerenciarSites1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(btHabilitar))
                .addGap(18, 18, 18)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHabilitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHabilitarActionPerformed

    private void btGerenciarSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarSitesActionPerformed
        new FormSites().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btGerenciarSitesActionPerformed

    private void btGerenciarSites1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarSites1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerenciarSites1ActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (txtDescricao.getText().isEmpty()) {
            AlertUtil.alert("Preencha a descrição do projeto");
            return;
        }

        if (siteDAO.getSitesSelectedFromJList(listSites).isEmpty()) {
            AlertUtil.alert("Selecione um site!");
            return;
        }
        this.project.setDescription(txtDescricao.getText());
        this.project.setSites(siteDAO.getSitesSelectedFromJList(listSites));

        if (this.project.getId() == null) {
            System.out.println("save!");
            projectDAO.save(project);
        } else {
            System.out.println("update!");
            projectDAO.update(project);
        }

        AlertUtil.alert("Feito com sucesso!");
        new GerenciarProjetos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProjetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerenciarSites;
    private javax.swing.JButton btGerenciarSites1;
    private javax.swing.JButton btHabilitar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listSites;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
